### PR TITLE
Checksum is case sensitive and should be in upper case

### PR DESCRIPTION
**Pull request by pakerfeldt**
I ran into this issue myself recently and noticed others having the same problem: https://github.com/dustindclark/homebridge-envisalink/issues/3

### CODE REVIEW

**Comment by entrocode** [comment]
@pakerfeldt sorry that took so long for me to get to.  Thanks for the PR!

**Comment by dustindclark** [comment]
@entrocode , any chance we can get this published so the I can upgrade and close my bug downstream?  Thanks!

**Comment by entrocode** [comment]
@dustindclark I merged this on December 10th

**Comment by pakerfeldt** [comment]
@entrocode I believe @dustindclark is referring to the npm package that still hasn't been bumped.
https://www.npmjs.com/package/nodealarmproxy

**Comment by entrocode** [comment]
@dustindclark @pakerfeldt I ran publish the other day... lost track it, sorry about that

**Comment by dustindclark** [comment]
@martzcodes thank you!

**Pull request merged**
